name: Windows Compile
on: [workflow_dispatch]
jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtwebengine'

    - name: Create Makefile
      run: 
        qmake PowerVelo.pro -spec winrt-x64-msvc2017
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: build\ 
