name: Linux Compile

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  build_linux:
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Linux Environment Setup - install software-properties-common - ppa pre-req
      run: sudo apt-get install software-properties-common -y -qq
    - name: Linux Environment Setup - install qt ppa
      run: sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic -y && sudo apt-get update -y
    - name: Linux Environment Setup - install python3
      run:  sudo apt-get install python3-pip --yes
    - name: Install QT 5.12.x - part 1
      run: sudo apt-get install qt5-default qt5-qmake qt512base qt512tools libqwt-qt5-6 qt512serialport qt512svg qt512multimedia qt512connectivity qt512webengine libqt5webkit5-dev qt512charts-no-lgpl qt512networkauth-no-lgpl qt512translations qtdeclarative5-dev-tools libqwt-qt5-dev qtwebengine5-dev vlc libvlc-dev libvlccore-dev libsfml-dev libusb-1.0-0-dev -y
    - name: Install QT 5.12.x - part 2
      run: sudo /opt/qt512/bin/./qt512-env.sh
    - name: Install build essentials to compile VLC-Qt
      run: sudo apt-get install build-essential cmake debhelper
    - name: Build VLC-Qt
      run: cd /tmp && git clone https://github.com/vlc-qt/vlc-qt && cd vlc-qt && dpkg-buildpackage -us -uc
    - name: Install VLC-Qt
      run: sudo apt install /tmp/libvlc-qt-core2_1.2.0-1_amd64.deb /tmp/libvlc-qt-widgets2_1.2.0-1_amd64.deb /tmp/libvlc-qt-qml2_1.2.0-1_amd64.deb /tmp/libvlc-qt-dev_1.2.0-1_amd64.deb -y
    - name: Create Makefile
      run:  |
        qtchooser -list-versions
        qmake -version
        qmake PowerVelo.pro
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: build/
